# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ['14']
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run test

  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: '14'

      - run: npm install
      - run: npm run coverage

      # Runs a set of commands using the runners shell
      - name: Upload coverage reports
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
